export const ingredients = [
  {
    id: '1',
    name: 'Coffee Beans',
    price: 3.5,
    description: 'Roasted beans used to brew fresh coffee drinks.',
    img : '../Images/beans.jpg',
    isInStock: true,
  },
  {
    id: '2',
    name: 'Water',
    price: 0.2,
    description: 'Fresh, filtered water essential for all coffee types.',
    img : '../Images/water.jpg',
    isInStock: true,
  },
  {
    id: '3',
    name: 'Cinnamon',
    price: 0.8,
    description: 'Spicy-sweet powder added for aroma and flavor.',
    img : '../Images/cinnamon.webp',
    isInStock: true,
  },
  {
    id: '4',
    name: 'Chocolate',
    price: 1.5,
    description: 'Rich, sweet cocoa used in mochas and blends.',
    img : '../Images/chocolate.jpg',
    isInStock: true,
  },
  {
    id: '5',
    name: 'Steamed Milk',
    price: 1.2,
    description: 'Heated milk for smooth, creamy coffee drinks.',
    img : '../Images/steamedmilk.jpg',
    isInStock: true,
  },
  {
    id: '6',
    name: 'Milk Foam',
    price: 0.7,
    description: 'Frothed milk topping for cappuccinos and macchiatos.',
    img : '../Images/milk foam.webp',
    isInStock: true,
  },
  {
    id: '7',
    name: 'Cocoa Powder',
    price: 0.9,
    description: 'Dusting chocolate used for topping cappuccinos.',
    img : '../Images/cocoa powder.jpg',
    isInStock: true,
  },
  {
    id: '8',
    name: 'Hot Water',
    price: 0.2,
    description: 'Boiled water used to dilute espresso shots.',
    img : '../Images/hot water.png',
    isInStock: true,
  },
  {
    id: '9',
    name: 'Vanilla Ice Cream',
    price: 2.0,
    description: 'Cold dessert added to make affogato coffee.',
    img : '../Images/icecream.jpg',
    isInStock: true,
  },
  {
    id: '10',
    name: 'Whiskey',
    price: 4.5,
    description: 'Strong liquor used in Irish coffee recipes.',
    img : '../Images/whiskey.webp',
    isInStock: true,
  },
  {
    id: '11',
    name: 'Sugar',
    price: 0.3,
    description: 'Sweetens coffee drinks like Irish coffee and lattes.',
    img : '../Images/sugar.webp',
    isInStock: true,
  },
  {
    id: '12',
    name: 'Cream',
    price: 1.0,
    description: 'Thick dairy topping for rich and smooth taste.',
    img : '../Images/cream.jpg',
    isInStock: true,
  },
  {
    id: '13',
    name: 'Coarse Coffee',
    price: 3.5,
    description: 'Large ground beans ideal for cold brewing methods.',
    img : '../Images/coarse coffee.png',
    isInStock: true,
  },
  {
    id: '14',
    name: 'Cold Water',
    price: 0.2,
    description: 'Used in cold brew to steep coarse coffee grounds.',
    img : '../Images/coldwater.jpg',
    isInStock: true,
  }
];
